<?php

/**
 * @file Catman Invoice Email code
 */


/**
 * Implements hook_form_FORM_ID_alter()
 */
function catman_invoice_email_form_variable_group_form_alter(&$form, &$form_state) {
  if ($form_state['build_info']['args'][0] == 'commerce_email') {
    $form['tokens'] = array(
      '#markup' => theme('token_tree', array('token_types' => array('commerce-order', 'commerce-customer-profile', 'catman-invoice'), '#global_types' => FALSE)),
      '#weight' => 99999
    );
  }
}
